### ISSUE TITLE
Text field not disappearing

### ISSUE THREAD

**Issue by sachinbijadi** [AngelaIp/aras-hyperlinks#1]

**Comment by sachinbijadi** [comment]
Clickable hyperlink appears, but the text box does not disappear, and appears underneath the hyperlink when form is unlocked

**Comment by AngelaIp** [comment]
Do you use the same property "web_site" or do you use a custom text box? Code was written in SP11 but is simple enough that it should also work in other verisons.

**Comment by sachinbijadi** [comment]
Ok I had used different property names, so maybe I didnt edit that in all places in the js code. Now I changed the property name for my item types to web_site like in your sample, and the method works! Thanks
